build:
  g++ `pkg-config --cflags --libs gtk+-3.0` -o cir cir.cpp `pkg-config --cflags --libs gtk+-3.0`
  g++ `pkg-config --cflags --libs gtk+-3.0` -o sum sum.cpp `pkg-config --cflags --libs gtk+-3.0`
  g++ `pkg-config --cflags --libs gtk+-3.0` -o time time.cpp `pkg-config --cflags --libs gtk+-3.0`
clear:
  rm sum cir time
